[project]
name = "skand-explo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "viseryon", email = "viseryon@users.noreply.github.com" }]
requires-python = ">=3.11"
dependencies = [
    "aiohappyeyeballs==2.4.0",
    "aiohttp==3.10.5",
    "aiosignal==1.3.1",
    "attrs==24.2.0",
    "beautifulsoup4==4.12.3",
    "bleach==6.1.0",
    "certifi==2024.8.30",
    "charset-normalizer==3.3.2",
    "contourpy==1.3.0",
    "cssselect==1.2.0",
    "cssutils==2.11.1",
    "cycler==0.12.1",
    "dataframe-image>=0.2.7",
    "defusedxml==0.7.1",
    "fastjsonschema==2.20.0",
    "fonttools==4.53.1",
    "frozenlist==1.4.1",
    "geopandas>=1.1.0",
    "html2image==2.0.4.3",
    "idna==3.8",
    "ipykernel>=6.29.5",
    "jinja2==3.1.4",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2023.12.1",
    "jupyter-client==8.6.2",
    "jupyter-core==5.7.2",
    "jupyterlab-pygments==0.3.0",
    "kiwisolver==1.4.7",
    "lxml==5.3.0",
    "markupsafe==2.1.5",
    "matplotlib==3.9.2",
    "mistune==3.0.2",
    "more-itertools==10.4.0",
    "multidict==6.0.5",
    "nbclient==0.10.0",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "numpy==2.1.1",
    "packaging==24.1",
    "pandas==2.2.2",
    "pandocfilters==1.5.1",
    "pillow==10.4.0",
    "platformdirs==4.2.2",
    "pygments==2.18.0",
    "pyparsing==3.1.4",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.1",
    "pywin32==306",
    "pyzmq==26.2.0",
    "referencing==0.35.1",
    "requests==2.32.3",
    "rpds-py==0.20.0",
    "six==1.16.0",
    "soupsieve==2.6",
    "tinycss2==1.3.0",
    "tornado==6.4.1",
    "traitlets==5.14.3",
    "tzdata==2024.1",
    "urllib3==2.2.2",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "yarl==1.9.8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
skand_explo = "skand_explo.skanderbeg:main"
